# name: str()
# tags: array
# starter-files: str()
# type: str()
# level: str()
# cover-image: str()
# short-description: str()
# long-description: str()
# codedamn: 
#     helper-learning-path: str()
#     show-community-banner: bool()
#     playground-layout: str()
#     playground-image: str()

name: 
    required: true
    type: string
tags: 
    required: true
    type: list
starter-files:
    required: true  
    type: string
type:
    schema:
        required: true
        type: string
        enum: 
            - backend
            - frontend
            - fullstack   
level: 
    schema:
        required: true
        type: string
        enum: 
            - easy
            - medium
            - hard
cover-image:    
    required: true
    type: string
short-description:  
    required: true
    type: string
long-description:
    required: true
    type: string
codedamn:
    required: true
    type: dict
    schema: 
        helper-learning-path:
            schema: 
                required: true
                type: string
                enum: 
                    - backend
                    - frontend
                    - fullstack 
        show-community-banner:
            required: true
            type: boolean
        playground-layout:
            required: true
            type: string
        playground-image:
            schema: 
                required: true
                type: string
                enum: 
                    - html
                    - ethereum-v1
        